#!/usr/bin/with-contenv bash

if [ -n "$MARIADBLIB" ] && [ "$MARIADBLIB" = "true" ]; then
  echo "MARIADBLIB variable is true, installing the MariaDB library (libmariadb-dev)"
  apt-get update
  apt-get install -y libmariadb-dev
fi
